Adding two matrices

Addition is one of the easiest operation to carry out. The same hold true for matrices. Two matrices can be added only if they have the same dimensions. The elements at similar positions get added.

Given two matrices A and B having (n1 x m1) and (n2 x m2) dimensions respectively. Add A and B. 

Example 1:

Input:
n1 = 2, m1 = 3
A[][] = {{1, 2, 3},
         {4, 5, 6}}

n2 = 2, m2 = 3
B[][] = {{1, 3, 3},
         {2, 3, 3}}

Output: 2 5 6 6 8 9
Explanation:
The summation matrix of A and B is:
res[][] = {{2, 5, 6},
           {6, 8, 9}}
The output is generated by traversing each
row sequentially.
Example 2:

Input:
n1 = 3, m1 = 2
A[][] = {{1, 2},
         {3, 4}, 
         {5, 6}}

n2 = 3, m2 = 2
B[][] = {{1, 3},
          {3, 2},
         {3, 3}}
Output: 2 5 6 6 8 9
 

Your Task:
You dont need to read input or print anything. Complete the function sumMatrix() that takes A and B as input parameters and returns a matrix containing their sum. If the addition is not possible return an empty matrix.

 

Expected Time Complexity: O(n1 * m1)
Expected Auxiliary Space: O(n1 * m1) for the resultant matrix only. 

 

Constraints:
1 <= n1, m1, n2, m2 <= 30
0 <= Ai, Bi <= 100

Solution:

#User function Template for python3

def sumMatrix(A,B):
    n1 = len(A)
    m1 = len(A[0])
    n2 = len(B)
    m2 = len(B[0])
    result = []
    if(n1 == n2 and m1 == m2):
        result = [[0 for j in range(m1)] for i in range(n1)]
        for i in range(n1):
            for j in range(m1):
                result[i][j]=A[i][j]+B[i][j]
    return result
#{ 
#  Driver Code Starts
#Initial Template for Python 3

if __name__ == '__main__':
    t = int(input())
    for _ in range(t):

        n1,m1 = map(int,input().strip().split())
        A = [[0 for j in range(m1)] for i in range(n1)]
        line1 = [int(x) for x in input().strip().split()]       
        k = 0
        for i in range(n1):
            for j in range (m1):
                A[i][j]=line1[k]
                k+=1
       
        n2,m2 = map(int,input().strip().split())
        B = [[0 for j in range(m2)] for i in range(n2)]
        line2 = [int(x) for x in input().strip().split()]
        k=0
        for i in range(n2):
            for j in range (m2):
                B[i][j]=line2[k]
                k+=1

        ans = sumMatrix(A,B)
        if(len(ans) == 0):
            print(-1)
        else:
            for i in range(len(ans)):
                for j in range (len(ans[0])):
                    print(ans[i][j],end=' ')
            print() 

# } Driver Code Ends